import Button from "@/components/button";
import Modal from "@/components/Modal";
import Head from "next/head";
import Image from "next/image";
import { useState, useEffect } from "react";
import coffee from "../../public/coffee.png";
import plumber from "../../public/plumber.png";
import hair_dresser from "../../public/hair_dresser.png";
import yep from "../../public/Vector.png";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Slider from "react-slick";
import FeaturedBusinesses from "./FeaturedBusinesses";
export default function Home() {
  const images = [
    { name: "Coffee shop?", image: coffee },
    { name: "Plumber?", image: plumber },
    { name: "Hairdresser?", image: hair_dresser },
  ];
  const services = [
    "Doctors",
    "Plumbers",
    "Restaurants",
    "Tyre Dealers",
    "Creche",
    "Post offices",
    "Beauty salons",
    "Locksmiths",
    "Security services",
    "Schools",
    "Banks",
    "Accountants",
  ];
  const [worker, setWorker] = useState("");
  const [city, setCity] = useState("");
  const [currentImageIndex, setCurrentImageIndex] = useState(0);
  useEffect(() => {
    const intervalId = setInterval(() => {
      setCurrentImageIndex((currentImageIndex + 1) % images.length);
      console.log("Hello");
    }, 4000);
    return () => clearInterval(intervalId);
  }, [currentImageIndex]);

  const handleCheckWorkers = () => {
    console.log("checked workers");
  };

  const settings = {
    infinite: true,
    fade: true,
    autoplay: true,
    speed: 500,
    autoplaySpeed: 2000,
    cssEase: "linear",
    initialSlide: currentImageIndex,
  };

  const variableWidth = {
    // dots: true,
    infinite: true,
    slidesToShow: 6,
    slidesToScroll: 1,
    autoplay: true,
    autoplaySpeed: 2000,
    pauseOnHover: true,
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="p-2 max-w-[1320px] mx-auto ">
        <Slider {...settings}>
          {images.map((image, i) => (
            <div
              key={i}
              // className="flex justify-center items-center h-screen pt-10"
            >
              <div className="flex flex-col top-[141px] mx-auto w-[863px] h-[372px] absolute bg-slate-300 ">
                <div className="flex">
                  <h1 className="font-gordita leading-[65px] font-bold text-[65px] text-white ">
                    {image.name}
                  </h1>
                  <Image
                    src={yep}
                    alt="yep"
                    className="m-[20px]"
                    width={134}
                    height={71.92}
                  />
                </div>
                <p className="">Whatever you’re looking for, just yep it.</p>
                <form
                  className="border top-[293px] left-[229px] right-[227px] bg-white rounded-xl flex justify-between"
                  onSubmit={(e) => e.preventDefault()}
                >
                  <div className="flex items-center">
                    <svg
                      width="51"
                      height="51"
                      viewBox="0 0 51 51"
                      fill="none"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path
                        fill-rule="evenodd"
                        clip-rule="evenodd"
                        d="M29.7062 24.7532C29.7062 21.9918 27.4676 19.7532 24.7062 19.7532C21.9448 19.7532 19.7062 21.9918 19.7062 24.7532C19.7062 27.5146 21.9448 29.7532 24.7062 29.7532C27.4676 29.7532 29.7062 27.5146 29.7062 24.7532ZM24.7062 18.2532C28.2961 18.2532 31.2062 21.1633 31.2062 24.7532C31.2062 26.1652 30.756 27.4721 29.9912 28.538L33.4991 32.0459C33.8896 32.4365 33.8896 33.0696 33.4991 33.4602C33.1086 33.8507 32.4754 33.8507 32.0849 33.4602L28.5903 29.9656C27.5067 30.7744 26.1624 31.2532 24.7062 31.2532C21.1164 31.2532 18.2062 28.343 18.2062 24.7532C18.2062 21.1633 21.1164 18.2532 24.7062 18.2532Z"
                        fill="#01272F"
                      />
                    </svg>
                    <input
                      className="w-[255.96px] h-[22px] outline-0 font-medium text-md font-gordita"
                      type="text"
                      name="worker"
                      value={worker}
                      placeholder="Doctors, Plumbers, Beauty Salons..."
                      onChange={(event) => setWorker(event.target.value)}
                    />
                  </div>
                  <svg
                    className="bg-#809397 "
                    width="2"
                    height="50"
                    viewBox="0 0 2 50"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <line
                      opacity="0.3"
                      x1="0.981445"
                      y1="0.863281"
                      x2="0.981448"
                      y2="49.8633"
                      stroke="#809397"
                    />
                  </svg>
                  <div className="flex items-center">
                    <svg
                      width="51"
                      height="51"
                      viewBox="0 0 51 51"
                      fill="none"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path
                        d="M30.8602 24.0619C30.8602 28.6165 25.0043 32.5204 25.0043 32.5204C25.0043 32.5204 19.1484 28.6165 19.1484 24.0619C19.1484 22.5088 19.7654 21.0194 20.8636 19.9212C21.9618 18.823 23.4512 18.2061 25.0043 18.2061C26.5574 18.2061 28.0468 18.823 29.145 19.9212C30.2432 21.0194 30.8602 22.5088 30.8602 24.0619Z"
                        stroke="#01272F"
                        stroke-width="1.46293"
                        stroke-linecap="round"
                        stroke-linejoin="round"
                      />
                      <path
                        d="M25.0037 26.015C26.0817 26.015 26.9557 25.1411 26.9557 24.063C26.9557 22.985 26.0817 22.1111 25.0037 22.1111C23.9257 22.1111 23.0518 22.985 23.0518 24.063C23.0518 25.1411 23.9257 26.015 25.0037 26.015Z"
                        stroke="#01272F"
                        stroke-width="1.46293"
                        stroke-linecap="round"
                        stroke-linejoin="round"
                      />
                    </svg>

                    <input
                      className="w-[255.96px] h-[22px] outline-0 font-medium text-md font-gordita"
                      type="text"
                      name="city"
                      placeholder="Eg. Southdowns"
                      onChange={(event) => setCity(event.target.value)}
                    />
                  </div>
                  <button type="submit" onClick={handleCheckWorkers}>
                    <svg
                      width="51"
                      height="51"
                      viewBox="0 0 51 51"
                      fill="none"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <rect
                        x="0.441406"
                        y="0.363281"
                        width="50"
                        height="50"
                        rx="15"
                        fill="#01272F"
                      />
                      <path
                        fill-rule="evenodd"
                        clip-rule="evenodd"
                        d="M28.6486 24.1133C28.6486 21.628 26.6339 19.6133 24.1486 19.6133C21.6633 19.6133 19.6486 21.628 19.6486 24.1133C19.6486 26.5986 21.6633 28.6133 24.1486 28.6133C26.6339 28.6133 28.6486 26.5986 28.6486 24.1133ZM24.1486 17.6133C27.7384 17.6133 30.6486 20.5234 30.6486 24.1133C30.6486 25.5253 30.1983 26.8322 29.4336 27.8982L32.9415 31.4061C33.332 31.7966 33.332 32.4297 32.9415 32.8203C32.551 33.2108 31.9178 33.2108 31.5273 32.8203L28.0327 29.3257C26.9491 30.1345 25.6047 30.6133 24.1486 30.6133C20.5587 30.6133 17.6486 27.7031 17.6486 24.1133C17.6486 20.5234 20.5587 17.6133 24.1486 17.6133Z"
                        fill="white"
                      />
                    </svg>
                  </button>
                </form>
                <div className="top-[488px] flex flex-row flex-wraps gap-2 ">
                  {services.map((service, index) => (
                    <div
                      className="border text-white font-medium p-2 text-center rounded-lg"
                      key={index}
                      onClick={() => setWorker(service)}
                    >
                      {service}
                    </div>
                  ))}
                </div>
              </div>
              <Image
                className="object-center h-full rounded-2xl border-none"
                src={image.image}
                alt="yep-image"
              />
            </div>
          ))}
        </Slider>
        <div className="absolute top-[610px] left-[364px] w-[805px] h-[40px] text-center font-bold text-[30px]">
          <text className="text-white">
            Discover more by browsing the marketplace on Yep!
          </text>
        </div>
        <div className="absolute">
          <Slider {...variableWidth}>
            <div className="w-[175px] h-[195px] bg-slate-300">
              <h3>1</h3>
            </div>
            <div className="w-[175px] h-[195px]  bg-slate-300">
              <h3>2</h3>
            </div>
            <div className="w-[175px] h-[195px]  bg-slate-300">
              <h3>3</h3>
            </div>
            <div className="w-[175px] h-[195px]  bg-slate-300">
              <h3>4</h3>
            </div>
            <div className="w-[175px] h-[195px]  bg-slate-300">
              <h3>5</h3>
            </div>
            <div className="w-[175px] h-[195px]  bg-slate-300">
              <h3>6</h3>
            </div>
          </Slider>
        </div>
      </div>
    </>
  );
}

//medium
//large
//xl(configure 1320px)
//default mobile
